name: "Александр Е."
picture: "assets/img/picture.jpg"
bio: "Python Back End Developer"
meta:
  lang: "en"
  description: "Python Back End Developer"
  title: "Александр Е."
  author: "Александр Е."
  siteUrl: "https://Alex-Wo.github.io"
links:
  - name: "Github"
    url: "https://github.com/Alex-Wo"
  - name: "Сетка"
    url: "https://set.ki/cMB6cPu"
  - name: "Telegram"
    url: "https://t.me/AleksandrEg"
  - name: "Web Developers Work"
    url: "https://web-developers.work"
theme: "custom"