name: "Александр Егунов"
picture: "assets/img/picture.jpg"
bio: "Back End Web Developer"
stack: "Python / Django / PostgresSQL / linux / Git"
meta:
  lang: "en"
  description: "Back End Web Developer"
  title: "Александр Егунов"
  author: "Александр Егунов"
  siteUrl: "https://Alex-Wo.github.io"
links:
  - name: "Github"
    url: "https://github.com/Alex-Wo"
  - name: "Сетка"
    url: "https://set.ki/cMB6cPu"
  - name: "Telegram"
    url: "https://t.me/AleksandrEg"
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/egunov-it/"
theme: "custom"